apiVersion: v1
kind: Service
metadata:
  name: my-cluster-ip
spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: test
  ports:
    - name: http
      port: 30000
      targetPort: 80
      