apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-role-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: new-sa
roleRef:
  kind: ClusterRole
  name: cluster-role-myrole
  apiGroup: rbac.authorization.k8s.io

