apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-flask
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: new
  template:
    metadata: 
      labels:
        app: new
    spec:
      containers:
      - name: my-app-pods
        image: greeshma594/flask:latest
        ports:
        - containerPort: 80