apiVersion: v1 
kind: Service 
metadata:
  name: headless-svc
spec:
  clusterIP: None 
  selector:
    app: nginx-stateful
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080