apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: new-sa 
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role
  name: my-role 