apiVersion: v1 
kind: StatefulSet
metadata:
  name: nginx-stateful
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-stateful
  template:
    metadata: 
      labels: 
        app: nginx-stateful
    spec:
      containers:
      - name: nginx-cont-stateful
        image: nginx
        ports:
        - containerPort: 80