apiVersion: v1
kind: Service
metadata:
  name: svc-lb
spec: 
  type: LoadBalancer
  selector:
    app: new
    ports:
    - name: http
      port: 8080      #serviceport
      targetPort: 80  #containerport
      protocol: TCP